# -*- coding: utf-8 -*-
"""p04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HC1_FenOEtUCtvsXmY38FdGwTHPDXnz_
"""

#Nome: Gustavo de Oliveira Almeida 
#Matrícula: es86755
#Depois de o usuário entrar com as notas o programa irá fazer operações que especificam quantas dessas notas estão numa determinada faixa, no nosso caso entre 40 a 70.

import numpy as np
def main():
  tam_max = 60
  vmax = 100
  vmin = 0 
  notas = leiaNotas(vmin,vmax,tam_max)
  print("\nA quantidade de notas entre 40 e 70 é: ", filtra(notas))


def leiaNotas(vmin,vmax,tam_max): 
  notas = np.empty(tam_max)
  print('Entre com uma amostra de notas de 0 a 100 (-1 para terminar): ')
  i=0
  while i<=tam_max:
    notas[i] = input('')
    if notas[i] == -1:
      break;
    elif notas[i] > vmax:
      while notas[i] >vmax:
        print('Os valores devem estar entre 0 e 100. O valor incorreto digitado foi:', notas[i])
        notas[i] = input('Novo valor: ')
    elif notas[i] <vmin:
      while notas[i] < vmin:
        print('Você esta atribuindo valores menores que zero para as notas. O valor incorreto digitado foi:', notas[i])
        notas[i]= input('Novo valor: ')


    i = i+1
  return notas

def filtra(notas):
  filtromax = 70
  filtromin = 40
  contador = 0
  for i in range (0, len(notas)):
    if (notas[i] >= 40) and (notas[i]<= 70):
      contador = contador + 1
  return contador 


main() #Chamar a função princial
