# -*- coding: utf-8 -*-
"""p05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PtfCFLyWyymJr7WCBbbaiBGpIMPl679a
"""

#Nome: Gustavo de Oliveira Almeida
#Matricula: es86755
#Descrição do programa: O programa irá receber uma lista predefinida e irá organizá-la em ordem crescente pelo método da seleção direta.

def main():
  L = [43,36,25,18,18,14,9]
  #L = [36,18,43,9,18,25,14]
  ordena(L)
  print(L)


def ordena(L):
  for h in range(len(L)-1):
    j = minimo(L,h)
    a = L[j]
    L[j] = L[h]
    L[h] = a


def minimo(L,h):
  j = h
  for i in range(h+1, len(L)):
    if (L[j] > L[i]):
      j = i
  return j

main()