# -*- coding: utf-8 -*-
"""p06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1viLfuYaTAdmNEKb6DAO7JYQMYLKWjYnz
"""

#Nome: Gustavo de Oliveira Almeida  
#matricula: es86755
#Descrição: Nesse programa iremos simular uma fila e trataremos ela utilizando o método FIFO


def main():
  tamanho_fila = int(input("Quantos clientes serão atendidos inicialmente? "))
  opers = leiaOperacoes()
  simule(tamanho_fila,opers)



def leiaOperacoes():
 print(f'\nDigite F para adicionar um cliente ao fim da fila 1')
 print(f'Digite G para adicionar um cliente ao fim da fila 2')
 print(f'Digite A para realizar o atendimento em 1.')
 print(f'Digite B para realizar o atendimento em 2.')
 print(f'Digite S para sair.\n')
 operacao = input("Digite a Operação ou o conjunto delas: ").upper()
 return operacao

def simule(tamanho_fila,opers):
  if (tamanho_fila % 2 == 0):
    n = round(tamanho_fila/2)
  else:
    n = round(tamanho_fila/2 -0.5)    
  filaA = list(range(1, n+1))
  filaB = list(range(n+1, tamanho_fila+1))
  print(f'\nExistem {n} clientes na fila 1. \n Fila 1 atual: {filaA}')
  print(f'Existem {n+1} clientes na fila 2. \n Fila 2 atual: {filaB}')
  for i in opers:

    if (i == "A"):
      print(f'\nOperação: {i}')
      if len(filaA)>0:
        atendido = filaA.pop(0)
        print(f'\nCliente atendido {atendido}')
      else: 
        print(f'\nFila vazia!')

    elif (i == "B"):
      print(f'\nOperação: {i}')
      if len(filaB)>0:
        atendido = filaB.pop(0)
        print(f'\nCliente atendido {atendido}')
      else: 
        print(f'\nFila vazia!')

    elif (i == "F"):
      print(f'\nOperação: {i}')
      tamanho_fila = tamanho_fila + 1 
      filaA.append(tamanho_fila)

    elif (i == "G"):
      print(f'\nOperação: {i}')
      tamanho_fila = tamanho_fila+1 
      filaB.append(tamanho_fila)

    elif (i == "S"):
      print(f'\nOperação: {i}')
      print(f'\nFim da operação')
      break

    else: 
      print(f'\nOperação: {i}')
      print(f'Operação inválida! Digite apenas F, G, A, B ou S.')

    if (i == "A") or (i == "B") or (i == "F") or (i == "G"):
      print(f'\nExistem {len(filaA)} clientes na fila 1. \n Fila 1 atual: {filaA}')
      print(f'Existem {len(filaB)} clientes na fila 2. \n Fila 2 atual: {filaB}')
    


main()