# -*- coding: utf-8 -*-
"""p12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pvTB-aNGnaW6Ro_BGgMdsT4UKf7pKkXw
"""

#Nome: Gustavo de Oliveira Almeida
#Matricula: es86755
#Descrição: Pelo uso de dicionários o programa irá trabalhar o estoque de uma
#quitanda, fornecendo os produtos disponíveis em ordem alfabética e o valor 
#total em reais que há no estoque.

def main():
    estoque = {'tomate':[1000,2.30], 'alface': [500,0.45],
               'batata': [2150,1.20], 'feijão':[100,5.50]}
    estoque['arroz'] = [250,6.35]

    
    print(f'Produto    Preço  Quantidade')
    for produto in sorted(estoque):
        print(f'{produto} \t   {estoque[produto][1]:.2f}     {estoque[produto][0]}')
    print(f'\nValor total do estoque: {calculaValorTotal(estoque)}')




def calculaValorTotal(estoque):
    Total = 0
    for produto in estoque:
        Total = estoque[produto][0]*estoque[produto][1] + Total
    return Total


main()